/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevealRouteImport } from './routes/reveal'
import { Route as PlayerTwoRouteImport } from './routes/player-two'
import { Route as PlayerOneRouteImport } from './routes/player-one'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as IndexRouteImport } from './routes/index'

const RevealRoute = RevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerTwoRoute = PlayerTwoRouteImport.update({
  id: '/player-two',
  path: '/player-two',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerOneRoute = PlayerOneRouteImport.update({
  id: '/player-one',
  path: '/player-one',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/handoff': typeof HandoffRoute
  '/player-one': typeof PlayerOneRoute
  '/player-two': typeof PlayerTwoRoute
  '/reveal': typeof RevealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/handoff': typeof HandoffRoute
  '/player-one': typeof PlayerOneRoute
  '/player-two': typeof PlayerTwoRoute
  '/reveal': typeof RevealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/handoff': typeof HandoffRoute
  '/player-one': typeof PlayerOneRoute
  '/player-two': typeof PlayerTwoRoute
  '/reveal': typeof RevealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/handoff' | '/player-one' | '/player-two' | '/reveal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/handoff' | '/player-one' | '/player-two' | '/reveal'
  id: '__root__' | '/' | '/handoff' | '/player-one' | '/player-two' | '/reveal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandoffRoute: typeof HandoffRoute
  PlayerOneRoute: typeof PlayerOneRoute
  PlayerTwoRoute: typeof PlayerTwoRoute
  RevealRoute: typeof RevealRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reveal': {
      id: '/reveal'
      path: '/reveal'
      fullPath: '/reveal'
      preLoaderRoute: typeof RevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-two': {
      id: '/player-two'
      path: '/player-two'
      fullPath: '/player-two'
      preLoaderRoute: typeof PlayerTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-one': {
      id: '/player-one'
      path: '/player-one'
      fullPath: '/player-one'
      preLoaderRoute: typeof PlayerOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandoffRoute: HandoffRoute,
  PlayerOneRoute: PlayerOneRoute,
  PlayerTwoRoute: PlayerTwoRoute,
  RevealRoute: RevealRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
